import { defineType } from "sanity";

export const practices = defineType({
  name: "practices",
  title: "Practices",
  type: "document",
  fields: [
    { name: "id", title: "ID", type: "number" },
    { name: "name", title: "Name", type: "string" },
    { name: "doctorId", title: "Doctor ID", type: "number" },
    { name: "active", title: "Active", type: "boolean" },
    { name: "partner", title: "Partner", type: "boolean" },
    { name: "provider", title: "Provider", type: "boolean" },
    { name: "providerPlus", title: "Provider Plus", type: "boolean" },
    { name: "email", title: "Email", type: "string" },
    { name: "website", title: "Website", type: "string" },
    { name: "appointmentLink", title: "Appointment Link", type: "string" },
    { name: "phone", title: "Phone", type: "string" },
    { name: "address", title: "Address", type: "string" },
    { name: "streetNumber", title: "Street Number", type: "string" },
    { name: "suiteNumber", title: "Suite Number", type: "string" },
    { name: "route", title: "Route", type: "string" },
    { name: "city", title: "City", type: "string" },
    { name: "county", title: "County", type: "string" },
    { name: "state", title: "State", type: "string" },
    { name: "stateShort", title: "State Short", type: "string" },
    { name: "zip", title: "ZIP", type: "string" },
    { name: "country", title: "Country", type: "string" },
    { name: "countryShort", title: "Country Short", type: "string" },
    { name: "latitude", title: "Latitude", type: "number" },
    { name: "longitude", title: "Longitude", type: "number" },
    {
      name: "openingHours",
      title: "Opening Hours",
      type: "object",
      fields: [
        { name: "mo", title: "Monday", type: "string" },
        { name: "tu", title: "Tuesday", type: "string" },
        { name: "we", title: "Wednesday", type: "string" },
        { name: "th", title: "Thursday", type: "string" },
        { name: "fr", title: "Friday", type: "string" },
        { name: "sa", title: "Saturday", type: "string" },
        { name: "su", title: "Sunday", type: "string" },
      ],
    },
    {
      name: "socialMedia",
      title: "Social Media",
      type: "object",
      fields: [
        { name: "twitter", title: "Twitter", type: "string" },
        { name: "facebook", title: "Facebook", type: "string" },
        { name: "instagram", title: "Instagram", type: "string" },
      ],
    },
    { name: "createdAt", title: "Created At", type: "string" },
    { name: "updatedAt", title: "Updated At", type: "string" },
    { name: "image", title: "Image", type: "string" },
    {
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [{ type: "string" }],
    },
    {
      name: "products",
      title: "Products",
      type: "array",
      of: [{ type: "string" }],
    },
    {
      name: "productsFromOrder",
      title: "Products From Order",
      type: "array",
      of: [{ type: "string" }],
    },
    { name: "practiceDiscount", title: "Practice Discount", type: "string" },
    { name: "practiceLogo", title: "Practice Logo", type: "string" },
    { name: "practiceQrCode", title: "Practice QR Code", type: "string" },
    { name: "refersionLink", title: "Refersion Link", type: "string" },
    {
      name: "productPads",
      title: "Product Pads",
      type: "array",
      of: [{ type: "string" }],
    },
    { name: "displayType", title: "Display Type", type: "string" },
    {
      name: "practiceDiscount20",
      title: "Practice Discount 20",
      type: "string",
    },
  ],
});
