export const FramesData = [
  {
    id: "1",
    name: "Frame 1",
    material: "Wood",
    materialDescription: "High-quality oak wood",
    shape: "Round",
    size: "Medium",
    color: "Brown",
    gender: "Unisex",
    brand: "Timber Frames",
    price: 120.99,
    availability: true,
  },
  {
    id: "2",
    name: "Frame 2",
    material: "Metal",
    materialDescription: "Durable stainless steel",
    shape: "Square",
    size: "Large",
    color: "Silver",
    gender: "Men",
    brand: "SteelStyle",
    price: 99.99,
    availability: true,
  },
  {
    id: "3",
    name: "Frame 3",
    material: "Plastic",
    materialDescription: "Lightweight high-grade plastic",
    shape: "Oval",
    size: "Small",
    color: "Black",
    gender: "Women",
    brand: "Plastique",
    price: 49.99,
    availability: false,
  },
  {
    id: "4",
    name: "Frame 4",
    material: "Composite",
    materialDescription: "Hybrid of wood and plastic for durability",
    shape: "Rectangle",
    size: "Medium",
    color: "Blue",
    gender: "Kids",
    brand: "FunFrames",
    price: 75.49,
    availability: true,
  },
  {
    id: "5",
    name: "Frame 5",
    material: "Titanium",
    materialDescription: "Ultra-light and strong titanium",
    shape: "Round",
    size: "Large",
    color: "Gold",
    gender: "Unisex",
    brand: "Elite Eyewear",
    price: 199.99,
    availability: true,
  },
];

export const AccessoriesData = [
  {
    id: "A1",
    legacyId: "ENT1",
    entityId: "ACC1",
    name: "Protective Case",
    description: "Durable leather case for Frame 1",
    price: 20.99,
    availability: true,
  },
  {
    id: "A2",
    legacyId: "ENT1",
    entityId: "ACC2",
    name: "Cleaning Cloth",
    description: "Microfiber cloth for keeping Frame 1 clean",
    price: 5.99,
    availability: true,
  },
  {
    id: "A3",
    legacyId: "ENT1",
    entityId: "ACC3",
    name: "Lens Protector",
    description: "Anti-scratch protector for Frame 1 lenses",
    price: 12.99,
    availability: false,
  },
  {
    id: "A4",
    legacyId: "ENT2",
    entityId: "ACC4",
    name: "Travel Pouch",
    description: "Compact pouch for storing Frame 2",
    price: 15.49,
    availability: true,
  },
  {
    id: "A5",
    legacyId: "ENT2",
    entityId: "ACC5",
    name: "Replacement Screws",
    description: "Spare screws for Frame 2 maintenance",
    price: 7.49,
    availability: true,
  },
  {
    id: "A6",
    legacyId: "ENT3",
    entityId: "ACC6",
    name: "Cleaning Spray",
    description: "Specialized spray for cleaning Frame 3",
    price: 6.99,
    availability: true,
  },
  {
    id: "A7",
    legacyId: "ENT3",
    entityId: "ACC7",
    name: "Stylish Strap",
    description: "Adjustable strap for Frame 3",
    price: 10.99,
    availability: false,
  },
  {
    id: "A8",
    legacyId: "ENT4",
    entityId: "ACC8",
    name: "Kids Case",
    description: "Colorful case for Frame 4",
    price: 8.99,
    availability: true,
  },
  {
    id: "A9",
    legacyId: "ENT4",
    entityId: "ACC9",
    name: "Lens Wipes",
    description: "Disposable wipes for cleaning Frame 4 lenses",
    price: 3.99,
    availability: true,
  },
  {
    id: "A10",
    legacyId: "ENT5",
    entityId: "ACC10",
    name: "Luxury Case",
    description: "Premium case for Frame 5",
    price: 25.99,
    availability: true,
  },
  {
    id: "A11",
    legacyId: "ENT5",
    entityId: "ACC11",
    name: "Anti-fog Spray",
    description: "Spray to prevent fogging on Frame 5 lenses",
    price: 9.99,
    availability: false,
  },
];
