export const dummyData = [
  {
    id: "1",
    name: "Frame 1",
    material: "Wood",
    materialDescription: "High-quality oak wood",
    shape: "Round",
    size: "Medium",
    color: "Brown",
    gender: "Unisex",
    brand: "Timber Frames",
    price: 120.99,
    availability: true,
  },
  {
    id: "2",
    name: "Frame 2",
    material: "Metal",
    materialDescription: "Durable stainless steel",
    shape: "Square",
    size: "Large",
    color: "Silver",
    gender: "Men",
    brand: "SteelStyle",
    price: 99.99,
    availability: true,
  },
  {
    id: "3",
    name: "Frame 3",
    material: "Plastic",
    materialDescription: "Lightweight high-grade plastic",
    shape: "Oval",
    size: "Small",
    color: "Black",
    gender: "Women",
    brand: "Plastique",
    price: 49.99,
    availability: false,
  },
  {
    id: "4",
    name: "Frame 4",
    material: "Composite",
    materialDescription: "Hybrid of wood and plastic for durability",
    shape: "Rectangle",
    size: "Medium",
    color: "Blue",
    gender: "Kids",
    brand: "FunFrames",
    price: 75.49,
    availability: true,
  },
  {
    id: "5",
    name: "Frame 5",
    material: "Titanium",
    materialDescription: "Ultra-light and strong titanium",
    shape: "Round",
    size: "Large",
    color: "Gold",
    gender: "Unisex",
    brand: "Elite Eyewear",
    price: 199.99,
    availability: true,
  },
];
